[project]
name = "expense-management-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sarthak290210", email = "sarthakpannu10@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "mysql-connector-python>=26.7.0",
    "python-dotenv>=1.2.3",
    "streamlit>=1.64.0",
]

[project.scripts]
expense-management-system = "expense_management_system:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
